Web/Areas/WebApi/Controllers/MyPlanController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Common;
using IServices.Infrastructure;
using IServices.ISysServices;
using IServices.IUserServices;
using Models.UserModels;
using Newtonsoft.Json;

namespace Web.Areas.WebApi.Controllers
{
    public class MyPlanController :  AndroidBaseController<Plan>
    {
        //
        // GET: /WebApi/MyPlan/
        private readonly IUserInfo _iUserInfo;
        private readonly IPlanService _iPlanService;
        private readonly IUnitOfWork _unitOfWork;

        public MyPlanController(IUserInfo iUserInfo, IPlanService iPlanService, IUnitOfWork unitOfWork)
        {
            _iUserInfo = iUserInfo;
            _iPlanService = iPlanService;
            _unitOfWork = unitOfWork;
        }

        //根据起止时间、类型查询计划
        public ActionResult Index(DateTime? startTime, DateTime? endTime, string type, int pageIndex=1, int pageSize = 10)
        {
            var model = _iPlanService.GetAll().Where(a => a.UserId == _iUserInfo.UserId && a.EnterpriseId == _iUserInfo.EnterpriseId);
            if (string.IsNullOrEmpty(type) || !startTime.HasValue || !endTime.HasValue)
            {
                //不指定类型或没有起止时间，则获取所有未完成的计划
                model = model.Where(a => !a.Finish);
            }
            else
            {
                model = model.Where(a => a.PlanType == type && !((a.EndDate <= startTime) || (a.StartDate >= endTime)));
            }

            return GetModelDetail(model, pageIndex, pageSize);
        }

        //根据项目id查特定项目的所有计划
        public ActionResult InProject(Guid itemId, int pageIndex =1, int pageSize = 10)
        {
            var model = _iPlanService.GetAll().Where(a => !a.Deleted && a.ProjectInfoId == itemId);
            return GetModelDetail(model, pageIndex, pageSize); 
        }

        private ActionResult GetModelDetail(IQueryable<Plan> model, int pageIndex = 1, int pageSize = 10)
        {
            //排序
            model = model.OrderBy(a => a.Finish).ThenByDescending(a => a.CreatedDate);
            var result = model.Select(
            a =>
                new
                {
                    a.Id,
                    a.PlanType,
                    a.Raty,
                    a.UserId,
                    a.PlanTitle,
                    a.CreatedDate,
                    a.StartDate,
                    a.EndDate,
                    a.RemindTime,
                    a.Finish,
                    a.FinishTime,
                    a.Milestone,
                    a.SysUser.DisplayName,
                    a.ProjectInfoId,
                    a.ProjectInfo.ProjectName,
                    a.Remark
                }).ToPagedList(pageIndex, pageSize);

            return Content(JsonConvert.SerializeObject(result), "text/json");
        }

        public ActionResult Create(string entity)
        {
            var item = DeserializeObject(entity);
            _iPlanService.Save(null, item);
            _unitOfWork.Commit();
            return Content("True"); 
        }

        public ActionResult Edit(string entity)
        {
            var item = DeserializeObject(entity);
            _iPlanService.Save(item.Id, item);
            _unitOfWork.Commit();
            return Content("True"); 
        }

        public ActionResult Delete(Guid id)
        {
            _iPlanService.Delete(id);
            _unitOfWork.Commit();
            return Content("True");
        }

        public ActionResult Finish(Guid id)
        {
            _iPlanService.Finish(id);
            _unitOfWork.Commit();
            return Content("True");
        }

    }
}

Web/Areas/Platform/Views/Shared/Index.cshtml
@using System.Reflection
@using Web.Helper
@model System.Collections.IEnumerable
@using BootstrapSupport


<div>
    @if (Model.VisibleProperties().Any(a => a.Name == "Id"))
    {
        @Html.Partial("Button_Create", new { })
    }

    @Html.Partial("Button_Export", new { report = true, ordering = Request["ordering"], keyword = Request["keyword"] })

    
    <div class=" col-xs-3  pull-right">
        @Html.Partial("Search_Input")
    </div>
</div>
<div class="clearfix"></div>
<div>
    <table class="table table-bordered table-striped table-hover ">
        <thead>
            <tr>
                @foreach (PropertyInfo title in Model.VisibleProperties())
                {
                    if (title.Name == Model.GetType().GetGenericArguments()[0].IdentifierPropertyName())
                    {
                        <th>@lang.Edit</th>
                    }
                    else
                    {
                        <th>
                            @if (Request["ordering"] == title.Name)
                            {
                                @Ajax.ActionLink(title.GetLabel().ToSeparatedWords() + " ↓", null, new { keyword = Request["keyword"], ordering = title.Name + " desc" }, new AjaxOptions { UpdateTargetId = "Main" })
                            }
                            else if (Request["ordering"] == title.Name + " desc")
                            {
                                @Ajax.ActionLink(title.GetLabel().ToSeparatedWords() + " ↑", null, new { keyword = Request["keyword"], ordering = title.Name }, new AjaxOptions { UpdateTargetId = "Main" })
                            }
                            else
                            {
                                @Ajax.ActionLink(title.GetLabel().ToSeparatedWords() + "", null, new { keyword = Request["keyword"], ordering = title.Name }, new AjaxOptions { UpdateTargetId = "Main" })
                            }
                        </th>
                    }
                }
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                ViewData["DataList"] = item;
                <tr>
                    @foreach (PropertyInfo title in Model.VisibleProperties())
                    {
                        if (title.Name == item.IdentifierPropertyName())
                        {
                            <td>
                                @Html.Partial("Ajax_Edit_Verify", (Guid)item.GetId())
                            </td>
                        }
                        else
                        {
                            <td>
                                @Html.Display("DataList." + title.Name)
                            </td>
                        }
                    }
                </tr>
            }
        </tbody>
    </table>

    @Html.Raw(Ajax.MikePager((int)Model.GetType().GetProperty("PageIndex").GetValue(Model, null), (int)Model.GetType().GetProperty("PageSize").GetValue(Model, null), (int)Model.GetType().GetProperty("TotalCount").GetValue(Model, null)))
</div>

Web/Areas/Platform/Views/Shared/PlanItem.cshtml
@using System.CodeDom.Compiler
@using System.Resources
@using Web.Areas.Platform.Controllers
@model Models.UserModels.Plan

<h4>
    @if (Model.Finish)
    {
        <i class="fa fa-check-square-o"></i>
    }
    else
    {
        <i class="fa fa-square-o"></i>
    }

    @if (Model.ProjectInfo != null)
    {
        @Ajax.ActionLink(Model.ProjectInfo.ProjectName, "Details", "MyParticipateWork", new { id = Model.ProjectInfoId }, new AjaxOptions { UpdateTargetId = "Main" })
        <span>-</span>
    }

    @Ajax.ActionLink(Model.PlanTitle, "Details", "MyPlan", new { ViewBag.UpdateTargetId, Model.Id, Model.StartDate, Model.EndDate }, new AjaxOptions { UpdateTargetId = "Main" })

    @if (Model.Milestone)
    {
        <i class="fa fa-bookmark-o text-success"></i>
    }
</h4>
@if (!string.IsNullOrEmpty(Model.Remark))
{
    <div style="padding: 0 20px;">
        @Html.DisplayFor(a => Model.Remark)
    </div>
}
<small style="padding: 0 22px;">@Html.DisplayNameFor(a => a.Raty)：@Html.DisplayFor(a => a.Raty)
    创建时间：@Html.DisplayFor(a => Model.CreatedDate)
    创建人：@Html.Partial("SysUserDisplay", Model.SysUser)
    @if (Model.RemindTime.HasValue)
    {
        @("提醒：" + Html.DisplayFor(a => a.RemindTime))
    }
    @(Model.Finish ? "完成时间：" + Html.DisplayFor(a => Model.FinishTime) : "")
</small>

Web/Areas/Platform/Views/Shared/ProjectInfoItem.cshtml
@model Models.UserModels.ProjectInfo
<h4>
    @if (!Model.Public)
    {
        <i class="fa fa-lock"></i>
    }

    @Html.DisplayFor(a => a.ProjectInfoState.ProjectInfoStateName)

    @Ajax.ActionLink(Model.ProjectName, "Details", new { id = Model.Id, pageIndex = Request["pageIndex"] }, new AjaxOptions { UpdateTargetId = "Main" })

    @(!Model.Finish ? "" : "(" + lang.Finish + ")")
</h4>
<div>@Html.DisplayFor(modelItem => Model.ProjectObjective)</div>
<div class="muted">
    <span>@Html.DisplayFor(modelItem => Model.Raty)</span>
    <span>
        @Html.DisplayFor(modelItem => Model.StarTime)
    @if (Model.EndTime.HasValue)
    {
        <span>~</span>
        @Html.DisplayFor(modelItem => Model.EndTime)
    }
</span>

@if (!Model.Finish && Model.EndTime.HasValue)
{
    <span>剩余<span class="text-info lead">@(new TimeSpan(Model.EndTime.Value.Date.AddDays(1).AddSeconds(-1).Ticks - DateTime.Now.Ticks).TotalDays.ToString("0.0"))</span>天</span>
}
    <span>计划 <span class="text-info">@Model.Plans.Count(a => !a.Deleted)</span></span>
    <span>任务 <span class="text-info">@Model.ProjectTasks.Count(a => !a.Deleted)</span></span>
    <span>回复 <span class="text-info">@Model.ProjectInfoReplys.Count(a => !a.Deleted)</span></span>
    <span>成员 <span class="text-info">@Model.ProjectUsers.Count(a => !a.Deleted)</span></span>
    <span>文档 <span class="text-info">@Model.ProjectFiles.Count(a => !a.Deleted)</span></span>
</div>

Web/Areas/Platform/Views/Shared/ProjectTaskItem.cshtml
@model Models.UserModels.ProjectTask

<h4>
    @if (Model.Finish)
    {
        <i class="fa fa-check-square-o"></i>
    }
    else
    {
        <i class="fa fa-square-o"></i>
    }
    @if (Model.ProjectInfo != null)
    {
        @Ajax.ActionLink(Model.ProjectInfo.ProjectName, "Details", "MyParticipateWork", new { id = Model.ProjectInfoId }, new AjaxOptions { UpdateTargetId = "Main" })
        <span>-</span>
    }

    @Ajax.ActionLink(Model.ProjectTaskName, "Details", "MyProjectTask", new { id = Model.Id, displaytype = Request["displaytype"], finish = Request["finish"] }, new AjaxOptions { UpdateTargetId = "Main" })
</h4>

@if (!string.IsNullOrEmpty(Model.FileUrl))
{
    <div style="padding: 0 22px;">
        <span class="fa fa-file"></span>&nbsp;@Html.DisplayFor(a => Model.FileUrl)
    </div>
}

@if (!string.IsNullOrEmpty(Model.ProjectTaskObjective))
{
    <div style="padding: 0 22px;">
        @Html.DisplayFor(modelItem => Model.ProjectTaskObjective)
    </div>
}
<small style="padding: 0 22px;" ><span>计划时间：@Html.DisplayFor(modelItem => Model.BeginTime)

        <span>~</span>
        @Html.DisplayFor(modelItem => Model.EndTime)

    </span>
    @if (Model.Accept.HasValue)
    {
        if (Model.Accept.Value)
        {
            <span>接受时间：@Html.DisplayFor(modelItem => Model.AcceptTime)</span>
        }
        else
        {
            <span>拒绝时间：@Html.DisplayFor(modelItem => Model.AcceptTime)</span>
        }
    }

    @if (!Model.Finish)
    {
        <span>剩余</span>
        <span class="@(Model.EndTime > DateTime.Now ? "text-info" : "text-error") ">
            <strong>@(new TimeSpan(Model.EndTime.Date.AddDays(1).AddSeconds(-1).Ticks - DateTime.Now.Ticks).TotalDays.ToString("0.0"))</strong>
        </span>
        <span>天</span>
    }
    else
    {
        <span>完成时间：@Html.DisplayFor(modelItem => Model.FinishTime)</span>
    }


    <span>发布人：@Html.Partial("SysUserDisplay", Model.SendUser) </span>

    <span>负责人：@Html.Partial("SysUserDisplay", Model.SysUser) </span>

    <span>回复：@Model.ProjectTaskReplys.Count(a => !a.Deleted)</span>
</small>

<div class="clearfix"></div>
@foreach (var item1 in Model.ProjectTaskReplys.Where(a => !a.Deleted).OrderByDescending(a => a.CreatedDate))
{
    <blockquote>
        <div style="padding: 4px;">@item1.ProjectTaskReplyObjective</div>
        @if (!string.IsNullOrEmpty(item1.FileUrl))
        {
            <div style="padding: 4px;">
                <span class="fa fa-file"></span>&nbsp;@Html.DisplayFor(a => item1.FileUrl)
            </div>
        }
        <small>
            @item1.CreatedDate
            @Html.Partial("SysUserDisplay", item1.SysUser)
        </small>
    </blockquote>
}