Web/Areas/Platform/Controllers/ProjectFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IServices.Infrastructure;
using IServices.ISysServices;
using IServices.IUserServices;
using Models.UserModels;

namespace Web.Areas.Platform.Controllers
{
    public class ProjectFileController : Controller
    {
        private readonly IProjectFileService _iProjectFileService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserInfo _userInfo;

        public ProjectFileController(IProjectFileService iProjectFileService, IUnitOfWork unitOfWork, IUserInfo userInfo)
        {
            _iProjectFileService = iProjectFileService;
            _unitOfWork = unitOfWork;
            _userInfo = userInfo;
        }

        public ActionResult Index(Guid projectInfoId)
        {
            var model = _iProjectFileService.GetAll(a => a.ProjectInfoId == projectInfoId);
            ViewBag.projectInfoId = projectInfoId;
            ViewBag.UserId = _userInfo.UserId;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Guid? id, ProjectFile collection)
        {
            _iProjectFileService.Save(id, collection);
            _unitOfWork.Commit();
            return RedirectToAction("Index", new { collection.ProjectInfoId });
        }


        [HttpDelete]
        public ActionResult Delete(Guid id, Guid projectInfoId)
        {
            _iProjectFileService.Delete(id);
            _unitOfWork.Commit();
            return RedirectToAction("Index", new {  projectInfoId });
        }
    }
}

Web/Areas/Platform/Views/ProjectFile/Create.cshtml
@model Models.UserModels.ProjectFile

@using (Ajax.BeginForm("Create", "ProjectFile", new { projectInfoId = ViewBag.projectInfoId }, new AjaxOptions { UpdateTargetId = "ProjectFile" }, null))
{
    <div>

        @Html.TextBoxFor(a => a.ProjectFileName, null, new { placeholder = "请输入文件标题", @class = "form-control" })


        @Html.EditorFor(a => a.FileUrl)

        <input type="submit" value="@lang.Save" class="btn" />

    </div>


} 

Web/Areas/Platform/Views/ProjectFile/Index.cshtml
@using BootstrapSupport
@using Models.UserModels
@model IEnumerable<Models.UserModels.ProjectFile>
<blockquote>
    @Html.Partial("Create", new ProjectFile())
</blockquote>
<div class="clearfix"></div>
@foreach (var item in Model)
{
    <blockquote>
        <span class="pull-right">
            @if (item.UserId == ViewBag.UserId)
            {
                @Ajax.ActionLink(lang.Delete, "Delete", null, new { item.Id, item.ProjectInfoId }, new AjaxOptions { UpdateTargetId = "ProjectFile", HttpMethod = "Delete", Confirm = "您确定要删除该记录吗？该操作不可恢复！" }, new { @class = "btn btn-danger" })
            }

        </span>
        <p>@Html.DisplayFor(a => item.ProjectFileName)</p>

        @if (!string.IsNullOrEmpty(item.FileUrl))
        {
            <div>
                <span class="icon-file"></span>&nbsp;@Html.DisplayFor(a => item.FileUrl)
            </div>
        }
        <small>
            @item.CreatedDate
            用户：@Html.Partial("SysUserDisplay", item.SysUser)
        </small>
    </blockquote>
}