Web/Areas/Admin/Controllers/IndexController.cs
using System.Linq;
using System.Web.Mvc;
using Common;
using IServices.ISysServices;
using IServices.Infrastructure;
using Models.SysModels;
using Web.Helper;

namespace Web.Areas.Admin.Controllers
{
    public class IndexController : Controller
    {
        private readonly ISysControllerService _sysControllerService;
        private readonly ISysUserService _sysUserService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserInfo _userInfo;


        public IndexController(ISysControllerService sysControllerService, ISysUserService sysUserService, IUnitOfWork unitOfWork, IUserInfo userInfo)
        {
            _sysControllerService = sysControllerService;
            _sysUserService = sysUserService;
            _unitOfWork = unitOfWork;
            _userInfo = userInfo;

        }

        //
        // GET: /Platform/Index/

        public ActionResult Index()
        {
            var area = (string)RouteData.DataTokens["area"];
            var model = _sysControllerService.GetAllEnt()
                                     .Where(
                                         a =>
                                         a.Display && a.Enabled &&
                                         a.SysControllerSysActions.Any(
                                             b =>
                                             b.SysRoleSysControllerSysActions.Any(
                                                 c =>
                                                 c.SysRole.SysRoleSysUsers.Any(
                                                     d => d.SysUserId.Equals(_userInfo.UserId)))) &&
                                         a.SysArea.AreaName.Equals(area)).ToList();
            ViewBag.UserName = _sysUserService.GetById(_userInfo.UserId).UserName;
            return View(model);
        }

        //用户信息
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(ChangePassword item)
        {
            if (!ModelState.IsValid)
            {
                return View(item);
            }

            //验证原密码是否正确

            var user = _sysUserService.GetByUserNamePassword(_userInfo.UserId, item.OldPassword);
            if (user != null)
            {
                user.Password = item.NewPassword;
                _sysUserService.Update(user);
                _unitOfWork.Commit();
                ModelState.AddModelError("", "修改成功！");
            }
            else
            {
                ModelState.AddModelError("OldPassword", "原密码错误！");
            }

            return View();
        }



    }
}

Web/Areas/Platform/Controllers/ProjectInfoReportController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Common;
using IServices.ISysServices;
using IServices.IUserServices;
using Models.UserModels;

namespace Web.Areas.Platform.Controllers
{
    public class ProjectInfoReportController : Controller
    {
        private readonly IProjectInfoService _iProjectInfoService;
        private readonly IUserInfo _iUserInfo;

        public ProjectInfoReportController(IProjectInfoService iProjectInfoService, IUserInfo iUserInfo)
        {
            _iProjectInfoService = iProjectInfoService;
            _iUserInfo = iUserInfo;
        }

        // 项目信息统计报表
        // GET: /Platform/ProjectInfoReport/

        public ActionResult Index(string keyword, int pageIndex = 1)
        {
            IQueryable<ProjectInfo> model =
                _iProjectInfoService.GetAll(a => a.ProjectUsers.Any(b => b.SysUserId == _iUserInfo.UserId && !b.Follow));
            if (!string.IsNullOrEmpty(keyword))
            {
                model =
                    model.Where(
                        a =>
                            a.ProjectName.Contains(keyword) || a.ProjectObjective.Contains(keyword) ||
                            a.Tag.Contains(keyword) || a.ProjectUsers.Any(b => b.SysUser.UserName == keyword));
            }

            return View(model.ToPagedList(pageIndex));
        }

        public ActionResult Details(Guid id)
        {
            ProjectInfo item = _iProjectInfoService.GetById(id);
            return View(item);
        }
    }
}

Web/Areas/Platform/Views/ProjectInfoReport/Details.cshtml
@model Models.UserModels.ProjectInfo

<div>
    <div class="pull-right">
        @Ajax.ActionLink("返回", "Index", null, new AjaxOptions() { UpdateTargetId = "Main" }, new { @class = "btn" })
    </div>
    <blockquote>
        <h3>@Model.ProjectName</h3>
    </blockquote>
    <hr />
</div>
<div>

    <script src="~/Scripts/dhtmlxgantt/dhtmlxgantt.js"></script>
    <script src="~/Scripts/dhtmlxgantt/ext/dhtmlxgantt_tooltip.js"></script>
    <link href="~/Content/dhtmlxgantt/dhtmlxgantt.css" rel="stylesheet" />
    <script src="~/Scripts/dhtmlxgantt/locale/locale_cn.js"></script>
    <div id="gantt_here" style=' height:500px;'></div>
    <script type="text/javascript">

        var demo_tasks = {
            data: [

                @foreach (var item in Model.ProjectTasks.Where(a => !a.Deleted).Select(a => new { ProjectTaskName="（任务）"+a.ProjectTaskName, a.BeginTime, a.EndTime, a.Finish }).Concat(Model.Plans.Where(b => !b.Deleted).Select(b => new { ProjectTaskName = "（计划）"+b.PlanTitle, BeginTime = b.StartDate, EndTime = b.EndDate, Finish = b.Finish })).OrderBy(a=>a.BeginTime).ThenBy(a=>a.EndTime))
            {
  @Html.Raw(" {  \"text\": \"" + HttpUtility.JavaScriptStringEncode(item.ProjectTaskName) + "\", \"start_date\": \"" +(int) item.BeginTime.ToOADate() + "\",\"duration\": \"" +  Math.Ceiling((item.EndTime - item.BeginTime).TotalDays) + "\",\"progress\": " + (item.Finish ? 1 : 0) + "},")
            }
            ],
            links: []
        };

        gantt.config.columns = [
            { name: "text", label: "任务名称", width: "*", tree: true },
            { name: "start_date", label: "开始时间", align: "center", }
        ];

        gantt.config.fit_tasks = true;

        gantt.config.readonly = true;

        gantt.config.scale_unit = "month";
        gantt.config.date_scale = "%F, %Y";

        gantt.config.scale_height = 50;

        gantt.config.subscales = [
            { unit: "day", step: 1, width: "*", date: "%j日" }
        ];

        gantt.init("gantt_here");

        gantt.parse(demo_tasks);

    </script>
</div>

Web/Areas/Platform/Views/ProjectInfoReport/Index.cshtml
@using Common
@using Web.Helper
@model Common.PagedList<Models.UserModels.ProjectInfo>

<div>

    <blockquote class="col-lg-2 ">
        <h3>项目报表</h3>
    </blockquote><div class=" col-xs-3  pull-right">
        @Html.Partial("Search_Input")
    </div>

</div>

<div class="clearfix"></div>

<div>
    @foreach (var item in Model)
    {
        <blockquote style=" padding:10px; ">

            <p style="padding: 0 0 10px 0;">
                @Ajax.ActionLink(item.ProjectName, "Details", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "Main" })
            </p>
            <div>@Html.DisplayFor(modelItem => item.ProjectObjective)</div>
            <small>
                @Html.DisplayFor(modelItem => item.StarTime)
                @if (!item.Finish && item.EndTime.HasValue)
                {
                    <span>~</span>
                    @Html.DisplayFor(modelItem => item.EndTime)

                    <span>
                        剩余<span class="text-info lead">
                            @(new TimeSpan(item.EndTime.Value.Date.AddDays(1).AddSeconds(-1).Ticks - DateTime.Now.Ticks).TotalDays.ToString("0.0"))
                        </span>
                        天
                    </span>
                }
                <span>计划</span>  <span class="text-info">@item.Plans.Count</span>
                <span>任务</span>  <span class="text-info">@item.ProjectTasks.Count</span>
                <span>成员</span> <span class="text-info">@item.ProjectUsers.Count</span>
            </small>

        </blockquote>

    }
    @Html.Raw(Ajax.MikePager(Model))
</div>